version: '3.5'

services:
  broker-nginx:
    container_name: c-broker-nginx
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    networks:
      default:
        ipv4_address: 172.30.0.10

volumes:
  app_beta:
    external: true
    name: docker_app_beta

networks:
  default:
    external:
      name: broker_network