services:
    App\Monolog\Processor\WebProcessor:
        arguments:
            - '@request_stack'
        tags:
            - { name: monolog.processor, handler: telegram }

monolog:
    channels:
        - rest
        - sms
        - checker
        - sms
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            sms:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/sms/sms.log"
                channels: [ 'sms' ]
            rest:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/rest/rest.log"
                channels: [ 'rest' ]
            checker:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/checker/checker.log"
                channels: [ 'checker' ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
#            telegram:
#                type: telegram
#                level: error
#                token: "%env(MONOLOG_TELEGRAM_TOKEN)%"
#                channel: "%env(MONOLOG_TELEGRAM_CHANNEL)%"
#                split_long_messages: true
#                delay_between_messages: true

when@beta:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            rest:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/rest/rest.log"
                channels: [ 'rest' ]
            sms:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/sms/sms.log"
                channels: [ 'sms' ]
            checker:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/checker/checker.log"
                channels: [ 'checker' ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: telegram
                excluded_http_codes: [403, 404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            rotating_files:
                max_files: 10
                type: rotating_file
                path: "%kernel.logs_dir%/main.log"
                level: warning
                channels: [ '!request', '!security', '!export', '!postback', '!console' ]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            telegram:
                type: telegram
                token: "%env(MONOLOG_TELEGRAM_TOKEN)%"
                channel: "%env(MONOLOG_TELEGRAM_CHANNEL)%"
                split_long_messages: true
                delay_between_messages: true
            rest:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/rest/rest.log"
                channels: [ 'rest' ]
            sms:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/sms/sms.log"
                channels: [ 'sms' ]
            checker:
                type: rotating_file
                max_files: 4
                path: "%kernel.logs_dir%/checker/checker.log"
                channels: [ 'checker' ]