version: '3.5'

services:
  broker-beta:
    platform: linux/amd64
    container_name: c-broker-beta
    image: 'app_beta'
    build:
      context: ../
      args:
        APP_ENV_FILE: .env.beta
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8884:80'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - app_beta:/app
    networks:
      default:
        ipv4_address: 172.30.0.3

networks:
  default:
    external:
      name: broker_network

volumes:
  app_beta:
