version: '3.5'

services:
  broker-dev:
    platform: linux/amd64
    container_name: c-broker-dev
    image: webdevops/php-nginx-dev:8.2
    user: application
    working_dir: /app
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '80:80'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
#      php.short_open_tag: 'On'
      PHP_DISPLAY_ERRORS: 1
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 55375
      XDEBUG_START_WITH_REQUEST: 'yes'
      PHP_IDE_CONFIG: serverName=xdebug_server
    volumes:
      - ../:/app
    networks:
      default:
        ipv4_address: 172.30.0.5

networks:
  default:
    external:
      name: broker_network
