version: '3.5'

services:
  broker-prod:
    container_name: c-broker-prod
    image: 'app_prod'
    build:
      context: ../
      args:
        APP_ENV_FILE: .env.prod
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8883:80'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - app_prod:/app
    networks:
      default:
        ipv4_address: 172.30.0.2

networks:
  default:
    external:
      name: broker_network

volumes:
  app_prod:
