version: '3.5'

services:
  broker-prod:
    container_name: c-broker-prod
    image: 'app_prod'
    build:
      context: ../
      target: app_prod
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
      - postgres_host:postgres_host
    ports:
      - '8883:80'
    environment:
      ENV_FILE_NAME: .env.prod
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - app_prod:/app
    networks:
      default:
        ipv4_address: 172.30.0.2

networks:
  default:
    external:
      name: broker_network

volumes:
  app_prod:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
