version: '3'

services:
  broker-admin:
    container_name: c-broker-admin
    image: webdevops/php-nginx:8.2
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../:/app
  postgrest:
    container_name: c-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
       - ./docker/db/psql/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
