version: '3.5'

services:
  broker-dev:
    platform: linux/amd64
    container_name: c-broker-dev
    image: 'app_dev'
    build:
      context: ../
      target: app_dev
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8881:80'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
#      php.short_open_tag: 'On'
      PHP_DISPLAY_ERRORS: 1
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 55375
      XDEBUG_START_WITH_REQUEST: 'yes'
      PHP_IDE_CONFIG: serverName=xdebug_server
    volumes:
      - "app_dev:/app"
    networks:
      default:
        ipv4_address: 172.30.0.5

networks:
  default:
    external:
      name: broker_network

volumes:
  app_dev:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
