version: '3.5'

services:
  broker-beta:
    platform: linux/amd64
    container_name: c-broker-beta
    image: 'app_beta'
    build:
      context: ../
      target: app_beta
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8880:80'
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - "app_beta:/app"
    networks:
      default:
        ipv4_address: 172.30.0.3

volumes:
  app_beta:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
