version: '3.5'
services:
  broker-admin:
    container_name: c-broker-admin
    image: webdevops/php-nginx:8.2
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../:/app